### ISSUE TITLE
Can't  connect to Teamspeak Server Version 3.10.2

### ISSUE THREAD

**Issue by DSeeLP** [Manevolent/ts3j#14]
I can connect to my Teamspeak Server with Version 3.9.1 but not to 3.10.2

**Comment by DSeeLP** [comment]
It didn't works with version 0.2

**Comment by TDRMinecraft** [comment]
Maybe your software was outdated or you have some issues with protocols

**Comment by TDRMinecraft** [comment]
If you can describe me the error further, I can do some research
