### ISSUE TITLE
Get all clients in channel

### ISSUE THREAD

**Issue by DSeeLPYT** [Manevolent/ts3j#15]
How can i get all clients in a channel?

**Comment by Ekrahb** [comment]
`List<Client> clients = new ArrayList<Client>();
    	for (Client basicClient : client.listClients()) {
    		if (basicClient.getChannelId() == yourChannelID) {
    			clients.add(basicClient);
    		}
    	}`

**Comment by DSeeLPYT** [comment]
Thanks
