### ISSUE TITLE
Bot stops run only 2 seconds

### ISSUE THREAD

**Issue by Gamer08YT** [Manevolent/ts3j#19]
Hey, i used your Example Bot.
But if a start the Bot it plays only 2 Seconds a Sinus Tone or the MP3 file.
What can i do, because there is not so much Information or Documentation.

**Comment by Ekrahb** [comment]
Look at the code

**Comment by Gamer08YT** [comment]
Ohh thanks, that will be the reason for the Problem.

**Comment by Ekrahb** [comment]
Why shouldn't it be?

**Comment by nettnikl** [comment]
Hey, a bit late to the party here. But to not let this end in frustration for folks from search engines:
`new TeamspeakFastMixerSink(..., (int) AUDIO_FORMAT.getSampleRate() * AUDIO_FORMAT.getChannels() * 4, ...)`
This second parameter, the `bufferSizeInBytes`, seems to be only big enough for exactly one second (samplerate is the amount of samples per seconds etc). Increasing this helps!
