### ISSUE TITLE
Invalid issue

### ISSUE THREAD

**Issue by silvehawk** [Manevolent/ts3j#21]
Invalid issue

**Comment by silvehawk** [comment]
Is there any documentation on the format of the float[] stream expected by or necessary for TeamspeakFastMixerSink.write(...) ?

**Comment by Manevolent** [comment]
The format that TS3j uses for these floats is a -1.0 to 1.0 "interleaved" sample stream.  As a byte[], you are effectively encoding some values in a bitstream from the lowest possible value (-something) to the highest possible value (+something) -- this is how the waveform is generated.

What you'll likely need to do is convert your source bitstream to a target float stream, here's a class I've used to do this:

https://github.com/Manebot/audio/blob/master/src/main/java/io/manebot/plugin/audio/resample/SampleConverter.java

**Comment by Manevolent** [comment]
Here's a link to a page that explains this concept:
https://markheath.net/post/convert-16-bit-pcm-to-ieee-float
