### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by Bdoom** [Manevolent/ts3j#25]
Is this legal to use to host your own servers? I want to  use the ts3 sdk to implement voice chat for my game, but I'm not sure if this is legal or if we have to pay for the enterprise server or what? lol

**Comment by Manevolent** [comment]
The client code is entirely "clean room" and should not be illegal; I would assume that TeamSpeak GmbH would have copyright-striken this repository by now if they somehow had grounds to do so.

The server, on the other hand, is something I've intentionally "stubbed-out" and have **not** written code for on purpose.  You'll see that a server class exists in this repository, but has absolutely no logic on it whatsoever.  When someone develops a server and publishes that, I anticipate the organization developing TeamSpeak would get impacts to their bottom-line as far as enterprise/etc. sales are concerned (as open-source servers could potentially bypass licensing restrictions in some clever ways).  The client doesn't really do that; if anything, it does the opposite by encouraging use of TeamSpeak 3/5.

So, you may need to ask a legal professional if hosting an open-source/3rd-party server is something of concern to you.  I am aware of server platforms out there, but they are closed-source and require modified/patched clients.
