### ISSUE TITLE
Can't connected to passworded server

### ISSUE THREAD

**Issue by RedHeadEmile** [Manevolent/ts3j#28]
After a bit of search, I found that the option `client.password` is set in *LocalTeamspeakClientSocket* but in *LocalClientHandlerConnecting*, the option `client.server_password` is read

Is it a mistake ?

**Comment by Manevolent** [comment]
Looks like it, thanks for letting me know:

https://github.com/Manevolent/ts3j/commit/ac8e7cf6f33f1072744c33752dfc8c43dbc377fb
