### ISSUE TITLE
Play sound and save client identity

### ISSUE THREAD

**Issue by derkobold** [Manevolent/ts3j#3]
Hello.
I tried to write a bot, bot there are some problems with it. Could you please post a running workaround for sending audio und for saving the identity? If i save the public key there is the issue `could not validate client identity`.

**Comment by Manevolent** [comment]
Sure, I'll put together ident export and get an example out there of sending/receiving audio.

**Comment by derkobold** [comment]
wow, thanks for the fast answer!

**Comment by derkobold** [comment]
13 mn and the best lib in the world. Great work dude

**Comment by derkobold** [comment]
`public void disconnect() throws IOException, TimeoutException, ExecutionException, InterruptedException {
    try {
      switch(this.getState()) {
      case RETRIEVING_DATA:
      case CONNECTING:
        this.waitForState(ClientConnectionState.CONNECTED, 10000L);
      case CONNECTED:
        this.writePacket(new PacketBody2Command(ProtocolRole.CLIENT, new SingleCommand("clientdisconnect", ProtocolRole.CLIENT, new CommandParameter[0])));
        this.waitForState(ClientConnectionState.DISCONNECTED, 30000L);
      }
    } finally {
      this.setState(ClientConnectionState.DISCONNECTED);
    }

  }`

could you overload the function for disconnecting with a leave message like 
`disconnect(String message) {
...
}`

**Comment by Manevolent** [comment]
`9d602a8` should have INI saving to disk (see: IdentitySaveTest.java), disconnect reasons, and a new example under a new `examples` folder for you to try out sending audio.
