### ISSUE TITLE
Initializing bot

### ISSUE THREAD

**Issue by An0nymusA** [Manevolent/ts3j#33]
So i was trying to setup bot and connect to server but a wasnt able to set identity and to setup the bot at all

**Comment by Manevolent** [comment]
Please provide more details.  What was your strategy for connecting to the server?  Please provide some code with your issue so I can help identify the problem here.

**Comment by An0nymusA** [comment]
i was using the example from git but i dont know what type of variables to put in the identity, password when server doesnt have one etc
(i dont have any code u was just trying to do this first step)

**Comment by An0nymusA** [comment]
some help ?

**Comment by DSeeLPYT** [comment]
To `identity` you need to pass an instance of 
`com.github.manevolent.ts3j.identity.LocalIdentity;` and when the server don‘t have an password. Don‘t call the method

**Comment by An0nymusA** [comment]
> To `identity` you need to pass an instance of
> `com.github.manevolent.ts3j.identity.LocalIdentity;` and when the server don‘t have an password, pass null or „“ to the method

and how to create the local identity

**Comment by An0nymusA** [comment]
> To `identity` you need to pass an instance of
> `com.github.manevolent.ts3j.identity.LocalIdentity;` and when the server don‘t have an password, pass null or „“ to the method

ive got something but this error showed up 
public class TeamSpeakClientBot {

>     public static void main(String args[]) {
>         LocalTeamspeakClientSocket client = new LocalTeamspeakClientSocket();
> 
>         LocalIdentity identity = null;
>         // Set up client
>         try {
>             identity = LocalIdentity.generateNew(10);
>         } catch (GeneralSecurityException e) {
>             e.printStackTrace();
>         }
>         try {
>             
>             client.setIdentity(identity);
>         }catch (Exception e){
>             System.out.println(1);
>             return;
>         }
>         //client.addListener(listener);
>         client.setNickname("test");
> 
>         try {
>             client.connect(
>                     new InetSocketAddress(
>                             InetAddress.getByName("localhost"),
>                             9987
>                     ),
>                     "",
>                     10000L
>             );
>         }catch (Exception e){
>             System.out.println(2);
>             return;
>         }
> 
>         // Subscribe to all channels
>         try {
>             client.subscribeAll();
>         }catch (Exception e){return;}
>     }
> 
> }

**Comment by An0nymusA** [comment]
Ok so i successfully joined to server but every time i join i have new identity how to prevent that

**Comment by Manevolent** [comment]
> ive got something but this error showed up

Those are warnings and can be ignored. That message is more for my information as a project maintainer and not something to concern over.

> yet i tried
> ` identity = LocalIdentity.load(new BigInteger(""));`
> But every time ive got this error

This isn't correct -- please refer to the LocalIdentity class and read the `load` and `save` methods, which do have some basic documentation, even if it is brief documentation.  They are mostly self-explanatory in terms of functionality, so I highly recommend looking over them carefully for usage information.

For more specific usage, see:
https://github.com/Manevolent/ts3j-musicbot/blob/master/src/main/java/com/github/manevolent/ts3j/musicbot/client/TeamspeakBot.java

Refer to lines 81, 82 and 84

Since this isn't an issue with the repository code and it seems like you just need some help getting going, I'm going to mark this ticket as such.

**Comment by An0nymusA** [comment]
so im trying to list all client or channels but every time i do so i got **insufficient client permissions** error, am i even able to list the channles without admin permission and i woild like to know if theres way to get current channel id

**Comment by An0nymusA** [comment]
BUMP
