### ISSUE TITLE
timeout waiting for CONNECTED state

### ISSUE THREAD

**Issue by mastedev** [Manevolent/ts3j#6]
Bot cannot connect to my teamspeak. On others works fine.
![image](https://user-images.githubusercontent.com/37625981/62131670-e15c1100-b2db-11e9-9612-ef0c39034fca.png)

**Comment by Manevolent** [comment]
https://github.com/Manevolent/ts3j/commit/9694a3f2c50116ee886e88048491dc0906c37a5d May of fixed this.
